#include "StdAfx.h"

__declspec(naked) void cResolution::Switch()
{
	static DWORD Offset1 = 0x41D8A7;

	_asm
	{
		MOV EAX, DWORD PTR DS : [MAIN_RESOLUTION];
		CMP EAX, 0x00;
		JNZ NEXT1;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_X], 640;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_Y], 480;
		JMP EXIT;
	NEXT1:
		CMP EAX, 0x01;
		JNZ NEXT2;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_X], 800;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_Y], 600;
		JMP EXIT;
	NEXT2:
		CMP EAX, 0x02;
		JNZ NEXT3;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_X], 1024;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_Y], 768;
		JMP EXIT;
	NEXT3:
		CMP EAX, 0x03;
		JNZ NEXT4;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_X], 1280;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_Y], 1024;
		JMP EXIT;
	NEXT4:
		CMP EAX, 0x04;
		JNZ NEXT5;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_X], 1360;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_Y], 768;
		JMP EXIT;
	NEXT5:
		CMP EAX, 0x05;
		JNZ NEXT6;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_X], 1440;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_Y], 900;
		JMP EXIT;
	NEXT6:
		CMP EAX, 0x06;
		JNZ NEXT7;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_X], 1600;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_Y], 900;
		JMP EXIT;
	NEXT7:
		CMP EAX, 0x07;
		JNZ NEXT8;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_X], 1680;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_Y], 1050;
		JMP EXIT;
	NEXT8:
		CMP EAX, 0x08;
		JNZ EXIT;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_X], 1920;
		MOV DWORD PTR DS : [MAIN_RESOLUTION_Y], 1080;
	EXIT:
		JMP[Offset1];
	}
}

__declspec(naked) void cResolution::Font()
{
	static DWORD Offset2 = 0x41E54D;
	static DWORD Resolution_ClipX = 0x54DCB0;
	static float Default = 2000.0f;

	_asm
	{
		MOV EAX, DWORD PTR DS : [MAIN_RESOLUTION_X];
		MOV DWORD PTR SS : [EBP - 0x1620], EAX;
		CMP DWORD PTR SS : [EBP - 0x1620], 640;
		JNZ NEXT1;
		MOV DWORD PTR DS : [MAIN_FONT_SIZE], 0x0C;
		JMP EXIT;
	NEXT1:
		CMP DWORD PTR SS : [EBP - 0x1620], 800;
		JNZ NEXT2;
		MOV DWORD PTR DS : [MAIN_FONT_SIZE], 0x0D;
		JMP EXIT;
	NEXT2:
		CMP DWORD PTR SS : [EBP - 0x1620], 1024;
		JNZ NEXT3;
		MOV DWORD PTR DS : [MAIN_FONT_SIZE], 0x0E;
		JMP EXIT;
	NEXT3:
		CMP DWORD PTR SS : [EBP - 0x1620], 1280;
		JNZ NEXT4;
		MOV DWORD PTR DS : [MAIN_FONT_SIZE], 0x0F;
		JMP EXIT;
	NEXT4:
		MOV DWORD PTR DS : [MAIN_FONT_SIZE], 0x0F;
		Push Default;
		Push Resolution_ClipX;
		Call[SetFloat];
		Add Esp, 0x08;
	EXIT:
		JMP[Offset2];
	}
}

cResolution Resolution;